redis:
  image: redis
  ports:
    - "6379:6379"
redisCommander:
  image: tenstartups/redis-commander
  command: --redis-host redis
  links:
    - redis:redis
  ports:
    - "8081:8081"
prometheus:
  image: prom/prometheus
  links:
    - redis:redis
#  volumes:
#    - ./prometheus.yml:/etc/prometheus/prometheus.yml
  ports:
    - "9090:9090"
sonarcollector:
  build: sonar
  volumes:
    - ./sonar:/app
